version: '3'
services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8000:80
      - 35729:35729
  backend:
    build: .
    command: --host 0.0.0.0 --reload
    environment:
      PYTHONPYCACHEPREFIX: /tmp
    volumes:
      - ./fx:/usr/src/app/fx:ro
  frontend:
    build: webapp
    environment:
      HOST: 0.0.0.0
    volumes:
      - ./webapp/public:/usr/src/app/public
      - ./webapp/src:/usr/src/app/src:ro
